"""Remove job_type column from Job model

Revision ID: ba24f7700aa5
Revises: 26dc3d44db66
Create Date: 2024-11-02 14:41:43.729532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba24f7700aa5'
down_revision = '26dc3d44db66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
